jwt_service:
  jwt_secret: "kmbase"
  
minio:
  endpoint: 'localhost:9000'
  access_key: 'kmbase'
  secret_key: 'kmbasepass'
  secure: false
  docs_bucket: 'kmbase'

text_chunker:
  chunk_size: 1500
  chunk_overlap: 200

embedding_model:
  endpoint: "http://localhost:11434"
  model_name: "nomic-embed-text"
  dimension: 768 

chat_model:
  endpoint: "http://localhost:11434"
  model_name: "llama3.1"
  stream: False

vector_store:
  cache_file: '../Stubs/faiss_index_cache.pkl'
  dimension: 768  
