jwt_service:
  jwt_secret: "kmbase"
  
minio:
  endpoint: 'localhost:9000'
  access_key: 'kmbase'
  secret_key: 'kmbasepass'
  secure: false
  docs_bucket: 'kmbase'

text_chunker:
  chunk_size: 1500
  chunk_overlap: 200

embedding_model:
  endpoint: "http://localhost:11434"
  model_name: "nomic-embed-text"
  dimension: 768 

chat_model:
  endpoint: "http://localhost:11434"
  model_name: "llama3.1"
  stream: False

vector_store:
  cache_file: '../Stubs/faiss_index_cache.pkl'
  dimension: 768  

langsmith:
  LANGCHAIN_TRACING_V2: "true"
  LANGCHAIN_ENDPOINT : "https://api.smith.langchain.com"
  LANGCHAIN_API_KEY : "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"
  LANGCHAIN_PROJECT : "kbasellms"

